name: Node.js CI/CD

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            SERVER_USER: ${{ secrets.SERVER_USER }}
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            REPO_PATH: ${{ secrets.REPO_PATH }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install sshpass
              run: sudo apt-get update && sudo apt-get install -y sshpass

            - name: Deploy to server via SSH
              run: |
                  sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -T $SERVER_USER@$SERVER_HOST << 'EOF'
                  cd ~/tg-farm
                  git pull

                  docker-compose down
                  docker-compose up -d --build
                  docker image prune -f
                  EOF
